set nocompatible

" Overall loock and feel
set number
set cursorline

" Default identation and textwidth
set colorcolumn=+1
"set textwidth=40
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent

" Search settings
set incsearch

" Highlighting
syntax on
highlight ExtraWhitespace ctermbg=darkgreen guibg=darkgreen
let w:xws = call('matchadd', ['ExtraWhitespace', '\s\+$'])
highlight SquishedCommas ctermbg=red guibg=red
let w:sc = call('matchadd', ['SquishedCommas', '\d\@!,\(\s\|\d\)\@!\($\)\@!'])
highlight UnknownPlaceholder ctermbg=red guibg=red
let w:uph = call('matchadd', ['UnknownPlaceholder', '\([XYZ?]\)\1\+'])

" Filetype related
filetype plugin indent on

" copy between sessions without clipboard
vmap <leader>y :w! /tmp/vimtmp<CR>
nmap <leader>p :r! cat /tmp/vimtmp<CR>

" Vundle - Vim Bundler
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" Add plugins
Plugin 'VundleVim/Vundle.vim'
Plugin 'editorconfig/editorconfig-vim'
Plugin 'AndrewRadev/linediff.vim'
call vundle#end()
