#!/usr/bin/env bash
# adopted from https://git.zx2c4.com/password-store/tree/contrib/dmenu/passmenu
# mainly adopted to work with the pass patch from janfred (auto copy)

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--notify" ]]; then
	notify=1
	shift
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | dmenu "$@")

[[ -n $password ]] || exit

if [[ $notify -eq 0 ]]; then
	pass show -c "$password" 2>/dev/null
else
	tmpfile=$(mktemp)
	pass show "$password" > $tmpfile
	cat $tmpfile | sed \$d | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/\\\\n/g' | while read line ; do notify-send -a pass -t 45000 "more information ($password)" "$line"; done
	rm $tmpfile
fi
